//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiProProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo_Empleado
    {
        public int ID_Cargo_Empleado { get; set; }
        public int ID_Cargo { get; set; }
        public int ID_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Terminación { get; set; }
        public int ID_Jornada { get; set; }
        public string TipoContrato { get; set; }
        public decimal Salario_Basico { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Jornada Jornada { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
