//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiProProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jornada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jornada()
        {
            this.Cargo_Empleado = new HashSet<Cargo_Empleado>();
        }
    
        public int ID_Jornada { get; set; }
        public Nullable<System.TimeSpan> Horario_inicio { get; set; }
        public Nullable<System.TimeSpan> Horario_Final { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo_Empleado> Cargo_Empleado { get; set; }
    }
}
