//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiProProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int ID_Nomina { get; set; }
        public int Total_Horas_Laboradas { get; set; }
        public Nullable<int> Extras_Diurnas { get; set; }
        public Nullable<int> Extras_Nocturnas { get; set; }
        public System.DateTime Fecha_Inicial_Pago { get; set; }
        public System.DateTime Fecha_Final_Pago { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
        public decimal Aporte_Salud { get; set; }
        public decimal Aporte_Pension { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
